// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModsDude.Server.Persistence.DbContexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModsDude.Server.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907171543_RepoNamesNotUnique")]
    partial class RepoNamesNotUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModsDude.Server.Domain.Invites.RepoInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrantedLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaximumUses")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Uses")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RepoId");

                    b.ToTable("RepoInvites");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Mods.ModVersion", b =>
                {
                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModId")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RepoId", "ModId", "Id");

                    b.HasIndex("RepoId", "ModId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("RepoId", "Updated", "ModId", "Id");

                    b.ToTable("ModVersions");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Profiles.Profile", b =>
                {
                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HeadRevision")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RepoId", "Id");

                    b.HasIndex("RepoId", "Name")
                        .IsUnique()
                        .HasFilter("\"ArchivedAt\" IS NULL");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Profiles.ProfileRevision", b =>
                {
                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ModCount")
                        .HasColumnType("integer");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceProfileId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SourceRevision")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Changes", "ModsDude.Server.Domain.Profiles.ProfileRevision.Changes#ProfileRevisionChanges", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Added")
                                .HasColumnType("integer");

                            b1.Property<int>("Changed")
                                .HasColumnType("integer");

                            b1.Property<int>("Removed")
                                .HasColumnType("integer");
                        });

                    b.HasKey("RepoId", "ProfileId", "Number");

                    b.ToTable("ProfileRevisions");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.RepoMemberships.RepoMembership", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "RepoId");

                    b.HasIndex("RepoId");

                    b.ToTable("RepoMemberships");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Repos.Repo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AdapterData", "ModsDude.Server.Domain.Repos.Repo.AdapterData#AdapterData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Configuration")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.ToTable("Repos");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Savegames.Savegame", b =>
                {
                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HeadVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("RepoId", "Id");

                    b.HasIndex("RepoId", "Name")
                        .IsUnique()
                        .HasFilter("\"ArchivedAt\" IS NULL");

                    b.HasIndex("RepoId", "ProfileId");

                    b.ToTable("Savegames");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Savegames.SavegameCheckout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndedReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SavegameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RepoId", "SavegameId")
                        .IsUnique()
                        .HasFilter("\"EndedAt\" IS NULL");

                    b.HasIndex("RepoId", "SavegameId", "TakenAt");

                    b.ToTable("SavegameCheckouts");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Savegames.SavegameVersion", b =>
                {
                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SavegameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int?>("BaseVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CheckoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProfileRevision")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("RepoId", "SavegameId", "Number");

                    b.HasIndex("RepoId", "ProfileId", "ProfileRevision");

                    b.HasIndex("RepoId", "SavegameId", "ContentHash");

                    b.ToTable("SavegameVersions");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ProfileLastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Invites.RepoInvite", b =>
                {
                    b.HasOne("ModsDude.Server.Domain.Repos.Repo", null)
                        .WithMany()
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Mods.ModVersion", b =>
                {
                    b.HasOne("ModsDude.Server.Domain.Repos.Repo", null)
                        .WithMany()
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("ModsDude.Server.Domain.Mods.ModAttribute", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("ModVersionRepoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ModVersionModId")
                                .HasColumnType("text");

                            b1.Property<string>("ModVersionId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .HasColumnType("text");

                            b1.HasKey("ModVersionRepoId", "ModVersionModId", "ModVersionId", "Id");

                            b1.ToTable("ModAttribute");

                            b1.WithOwner()
                                .HasForeignKey("ModVersionRepoId", "ModVersionModId", "ModVersionId");
                        });

                    b.OwnsMany("ModsDude.Server.Domain.Mods.ModImageReference", "Images", b1 =>
                        {
                            b1.Property<Guid>("ModVersionRepoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ModVersionModId")
                                .HasColumnType("text");

                            b1.Property<string>("ModVersionId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<string>("Rendition")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ModVersionRepoId", "ModVersionModId", "ModVersionId", "Id");

                            b1.ToTable("ModImageReference");

                            b1.WithOwner()
                                .HasForeignKey("ModVersionRepoId", "ModVersionModId", "ModVersionId");
                        });

                    b.Navigation("Attributes");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Profiles.Profile", b =>
                {
                    b.HasOne("ModsDude.Server.Domain.Repos.Repo", null)
                        .WithMany()
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Profiles.ProfileRevision", b =>
                {
                    b.HasOne("ModsDude.Server.Domain.Profiles.Profile", null)
                        .WithMany()
                        .HasForeignKey("RepoId", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ModsDude.Server.Domain.Profiles.ModDependency", "ModDependencies", b1 =>
                        {
                            b1.Property<Guid>("RepoId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("RevisionNumber")
                                .HasColumnType("integer");

                            b1.Property<string>("ModId")
                                .HasColumnType("text");

                            b1.Property<string>("ModVersionId")
                                .HasColumnType("text");

                            b1.Property<bool>("Locked")
                                .HasColumnType("boolean");

                            b1.HasKey("RepoId", "ProfileId", "RevisionNumber", "ModId", "ModVersionId");

                            b1.HasIndex("RepoId", "ModId", "ModVersionId");

                            b1.HasIndex("RepoId", "ProfileId", "RevisionNumber", "ModId")
                                .IsUnique();

                            b1.ToTable("ModDependency");

                            b1.HasOne("ModsDude.Server.Domain.Mods.ModVersion", "ModVersion")
                                .WithMany()
                                .HasForeignKey("RepoId", "ModId", "ModVersionId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("RepoId", "ProfileId", "RevisionNumber");

                            b1.Navigation("ModVersion");
                        });

                    b.Navigation("ModDependencies");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.RepoMemberships.RepoMembership", b =>
                {
                    b.HasOne("ModsDude.Server.Domain.Repos.Repo", null)
                        .WithMany("_memberships")
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModsDude.Server.Domain.Users.User", null)
                        .WithMany("RepoMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Savegames.Savegame", b =>
                {
                    b.HasOne("ModsDude.Server.Domain.Repos.Repo", null)
                        .WithMany()
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModsDude.Server.Domain.Profiles.Profile", null)
                        .WithMany()
                        .HasForeignKey("RepoId", "ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Savegames.SavegameCheckout", b =>
                {
                    b.HasOne("ModsDude.Server.Domain.Savegames.Savegame", null)
                        .WithMany()
                        .HasForeignKey("RepoId", "SavegameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Savegames.SavegameVersion", b =>
                {
                    b.HasOne("ModsDude.Server.Domain.Savegames.Savegame", null)
                        .WithMany()
                        .HasForeignKey("RepoId", "SavegameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModsDude.Server.Domain.Profiles.ProfileRevision", null)
                        .WithMany()
                        .HasForeignKey("RepoId", "ProfileId", "ProfileRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("ModsDude.Server.Domain.Savegames.SavegameDetail", "Details", b1 =>
                        {
                            b1.Property<Guid>("SavegameVersionRepoId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SavegameVersionSavegameId")
                                .HasColumnType("uuid");

                            b1.Property<int>("SavegameVersionNumber")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SavegameVersionRepoId", "SavegameVersionSavegameId", "SavegameVersionNumber", "Id");

                            b1.ToTable("SavegameVersionDetails", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SavegameVersionRepoId", "SavegameVersionSavegameId", "SavegameVersionNumber");
                        });

                    b.Navigation("Details");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Repos.Repo", b =>
                {
                    b.Navigation("_memberships");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Users.User", b =>
                {
                    b.Navigation("RepoMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
