// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModsDude.Server.Persistence.DbContexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModsDude.Server.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModsDude.Server.Domain.Mods.ModVersion", b =>
                {
                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModId")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RepoId", "ModId", "Id");

                    b.HasIndex("RepoId", "ModId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("ModVersions");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Profiles.Profile", b =>
                {
                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RepoId", "Id");

                    b.HasIndex("RepoId", "Name")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.RepoMemberships.RepoMembership", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "RepoId");

                    b.HasIndex("RepoId");

                    b.ToTable("RepoMemberships");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Repos.Repo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AdapterData", "ModsDude.Server.Domain.Repos.Repo.AdapterData#AdapterData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Configuration")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.ToTable("Repos");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ProfileLastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Mods.ModVersion", b =>
                {
                    b.HasOne("ModsDude.Server.Domain.Repos.Repo", null)
                        .WithMany()
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("ModsDude.Server.Domain.Mods.ModAttribute", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("ModVersionRepoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ModVersionModId")
                                .HasColumnType("text");

                            b1.Property<string>("ModVersionId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .HasColumnType("text");

                            b1.HasKey("ModVersionRepoId", "ModVersionModId", "ModVersionId", "Id");

                            b1.ToTable("ModAttribute");

                            b1.WithOwner()
                                .HasForeignKey("ModVersionRepoId", "ModVersionModId", "ModVersionId");
                        });

                    b.OwnsMany("ModsDude.Server.Domain.Mods.ModImageReference", "Images", b1 =>
                        {
                            b1.Property<Guid>("ModVersionRepoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ModVersionModId")
                                .HasColumnType("text");

                            b1.Property<string>("ModVersionId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.HasKey("ModVersionRepoId", "ModVersionModId", "ModVersionId", "Id");

                            b1.ToTable("ModImageReference");

                            b1.WithOwner()
                                .HasForeignKey("ModVersionRepoId", "ModVersionModId", "ModVersionId");
                        });

                    b.Navigation("Attributes");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Profiles.Profile", b =>
                {
                    b.HasOne("ModsDude.Server.Domain.Repos.Repo", null)
                        .WithMany()
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ModsDude.Server.Domain.Profiles.ModDependency", "ModDependencies", b1 =>
                        {
                            b1.Property<Guid>("RepoId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ModId")
                                .HasColumnType("text");

                            b1.Property<string>("ModVersionId")
                                .HasColumnType("text");

                            b1.Property<bool>("Locked")
                                .HasColumnType("boolean");

                            b1.HasKey("RepoId", "ProfileId", "ModId", "ModVersionId");

                            b1.HasIndex("RepoId", "ModId", "ModVersionId");

                            b1.HasIndex("RepoId", "ProfileId", "ModId")
                                .IsUnique();

                            b1.ToTable("ModDependency");

                            b1.WithOwner()
                                .HasForeignKey("RepoId", "ProfileId");

                            b1.HasOne("ModsDude.Server.Domain.Mods.ModVersion", "ModVersion")
                                .WithMany()
                                .HasForeignKey("RepoId", "ModId", "ModVersionId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("ModVersion");
                        });

                    b.Navigation("ModDependencies");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.RepoMemberships.RepoMembership", b =>
                {
                    b.HasOne("ModsDude.Server.Domain.Repos.Repo", null)
                        .WithMany("_memberships")
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModsDude.Server.Domain.Users.User", null)
                        .WithMany("RepoMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Repos.Repo", b =>
                {
                    b.Navigation("_memberships");
                });

            modelBuilder.Entity("ModsDude.Server.Domain.Users.User", b =>
                {
                    b.Navigation("RepoMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
