using ModsDude.Client.Core.Exceptions;
using ModsDude.Client.Core.GameAdapters.DynamicForms;
using ModsDude.Client.Core.Helpers;
using ModsDude.Client.Core.Models;
using System.Globalization;
using System.Xml;
using System.Xml.Linq;

namespace ModsDude.Client.Core.GameAdapters.Implementations.FarmingSimulatorV1;

public class FarmingSimulatorBaseSavegameAdapter : IBaseSavegameAdapter
{
    /// <summary>
    /// Farming Simulator has a fixed set of numbered folders and no way to add another, so a save
    /// always fills or displaces one that is already there.
    /// </summary>
    public bool CanCreateSlots => false;


    public IInstanceSavegameAdapter WithInstanceSettings(string serializedInstanceSettings)
    {
        var instanceSettings = FarmingSimulatorInstanceSettings.Deserialize(serializedInstanceSettings);
        instanceSettings.EnsureValid();
        return new FarmingSimulatorInstanceSavegameAdapter(instanceSettings);
    }

    public IInstanceSavegameAdapter WithInstanceSettings(DynamicForm instanceSettings)
    {
        if (instanceSettings is not FarmingSimulatorInstanceSettings settings)
        {
            throw new IncorrectGameAdapterSettingsTypeException<FarmingSimulatorInstanceSettings>(instanceSettings);
        }
        settings.EnsureValid();
        return new FarmingSimulatorInstanceSavegameAdapter(settings);
    }
}


public class FarmingSimulatorInstanceSavegameAdapter(FarmingSimulatorInstanceSettings instanceSettings)
    : FarmingSimulatorBaseSavegameAdapter, IInstanceSavegameAdapter
{
    /// <summary>
    /// The game offers this many slots and no more. A number about one game, which is exactly why it
    /// lives here and why <see cref="IInstanceSavegameAdapter.GetSlots"/> hands back a list - nothing
    /// above this file has to know it.
    /// </summary>
    private const int _slotCount = 20;

    /// <summary>
    /// The file every started save has, and the one that names it. Its absence is how an empty slot
    /// is told from an occupied one.
    /// </summary>
    private const string _careerSavegameFile = "careerSavegame.xml";

    /// <summary>
    /// Where the players who have connected are recorded. The career file says nothing about
    /// multiplayer, so this is the only place that question can be answered from.
    /// </summary>
    private const string _farmsFile = "farms.xml";

    /// <summary>
    /// Regenerated by the game from the save beside it, so it is bulk that would make every check-in
    /// bigger and make the content hash differ for a reason nobody played.
    /// </summary>
    private static readonly string[] _excludedFileNames = ["screenshot.png"];


    private string GameDataFolder => instanceSettings.GameDataFolder
        ?? throw new InvalidOperationException("Instance settings carry no game data folder.");


    public string GetSlotPath(SavegameSlotId slot)
    {
        return Path.Combine(GameDataFolder, slot.Value);
    }

    /// <summary>
    /// Every slot, in the order the game numbers them.
    /// </summary>
    /// <remarks>
    /// Read in parallel, capped the way the mod scan is: this is disk bound, so a handful at a time
    /// is as quick as twenty, and the thread pool belongs to the rest of the app too. Indexed rather
    /// than collected, so the results keep the slot order rather than the order they finished in.
    /// </remarks>
    public Task<IReadOnlyList<SavegameSlot>> GetSlots(CancellationToken cancellationToken)
    {
        return Task.Run<IReadOnlyList<SavegameSlot>>(() =>
        {
            var slots = new SavegameSlot[_slotCount];

            var options = new ParallelOptions
            {
                MaxDegreeOfParallelism = Environment.ProcessorCount,
                CancellationToken = cancellationToken
            };

            Parallel.For(0, _slotCount, options, i =>
            {
                var id = new SavegameSlotId($"savegame{i + 1}");
                slots[i] = ReadSlot(id, GetSlotPath(id), cancellationToken);
            });

            return slots;
        }, cancellationToken);
    }

    public bool BelongsInPackedSave(string relativePath)
    {
        return !_excludedFileNames.Contains(Path.GetFileName(relativePath), StringComparer.OrdinalIgnoreCase);
    }


    /// <summary>
    /// One slot, described from its career file and the farms beside it.
    /// </summary>
    /// <remarks>
    /// <b>Degrades rather than throws</b>, and always in the same direction. A slot whose career file
    /// is missing is empty; one whose career file will not parse, or that a running game is writing,
    /// is <b>occupied and unnamed</b>. Reporting it as empty is the single mistake that matters here,
    /// because an empty slot is the one the engine writes to without asking. Every detail is likewise
    /// optional - a field this adapter cannot read costs that one line and nothing else.
    /// </remarks>
    internal static SavegameSlot ReadSlot(SavegameSlotId id, string slotPath, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var careerFile = Path.Combine(slotPath, _careerSavegameFile);

        if (!File.Exists(careerFile))
        {
            return new SavegameSlot(id, null, false, []);
        }

        var maybeCareer = ReadCareer(careerFile);
        if (maybeCareer.HasValue is false)
        {
            return new SavegameSlot(id, null, true, []);
        }

        var career = maybeCareer.Value;
        var settings = Maybe.From(career.Element("settings"));

        var name =
            from element in settings
            from savegameName in Maybe.From(element.Element("savegameName"))
            let value = savegameName.Value.Trim()
            where string.IsNullOrWhiteSpace(value) is false
            select value;

        return new SavegameSlot(
            id,
            name.HasValue ? name.Value : null,
            true,
            ReadDetails(career, settings, slotPath, careerFile));
    }


    /// <summary>
    /// What this game is worth saying about a save, in the order somebody reads it: where they are
    /// playing, when they last did, how long they have been at it, and then the rest.
    /// </summary>
    private static IReadOnlyList<SavegameDetail> ReadDetails(
        XElement career, Maybe<XElement> settings, string slotPath, string careerFile)
    {
        var details = new List<SavegameDetail>();

        void Add(string detailId, string label, string? value)
        {
            if (string.IsNullOrWhiteSpace(value) is false)
            {
                details.Add(new SavegameDetail(detailId, label, value.Trim()));
            }
        }

        Add(SavegameDetail.Ids.Map, "Map", Text(settings, "mapTitle"));

        // The game's own record of when it was last written, which stays honest where copying the
        // save between machines has rewritten the file's own timestamp. That timestamp is the
        // fallback, because a save with no saveDate still has a "when" worth showing.
        Add(SavegameDetail.Ids.LastPlayed, "Last played",
            Text(settings, "saveDate") ?? LastWrittenText(careerFile));

        Add(SavegameDetail.Ids.Started, "Started", Text(settings, "creationDate"));

        // Under <statistics>, not <settings> - which is where this used to look, so every slot has
        // been silently reporting no playtime at all.
        var statistics = Maybe.From(career.Element("statistics"));

        Add(SavegameDetail.Ids.Playtime, "Played", Playtime(Text(statistics, "playTime")));
        Add(SavegameDetail.Ids.Money, "Money", Money(Text(statistics, "money")));
        Add(SavegameDetail.Ids.Difficulty, "Difficulty", Difficulty(Text(settings, "economicDifficulty")));
        Add(SavegameDetail.Ids.Multiplayer, "Multiplayer", Multiplayer(slotPath));

        return details;
    }

    /// <summary>
    /// Whether more than one person has ever joined, counted from the farms' player lists.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The career file records nothing about multiplayer, so this comes from <c>farms.xml</c>, where
    /// every farm keeps the players that have connected to it. One player is a save somebody has
    /// only ever played alone; more than one is a save that has been shared.
    /// </para>
    /// <para>
    /// <b>A heuristic, and worded as one.</b> It answers "has anybody else been in here", which is
    /// what somebody about to publish a save is actually asking. It cannot tell a game that was
    /// hosted and never joined from a singleplayer one, and does not pretend to.
    /// </para>
    /// </remarks>
    private static string? Multiplayer(string slotPath)
    {
        var farmsFile = Path.Combine(slotPath, _farmsFile);

        if (File.Exists(farmsFile) is false)
        {
            return null;
        }

        var maybeFarms = ReadXml(farmsFile);
        if (maybeFarms.HasValue is false)
        {
            return null;
        }

        // Distinct across every farm: one person who has joined two farms is still one person, and
        // the shop farm carries no players at all.
        var players = maybeFarms.Value
            .Descendants("player")
            .Select(x => (string?)x.Attribute("uniqueUserId"))
            .Where(x => string.IsNullOrWhiteSpace(x) is false)
            .Distinct(StringComparer.Ordinal)
            .Count();

        return players switch
        {
            0 => null,
            1 => "No, only ever played alone",
            _ => $"Yes, {players} players have joined"
        };
    }

    private static string? Text(Maybe<XElement> parent, string name)
    {
        if (parent.HasValue is false)
        {
            return null;
        }

        var value = parent.Value.Element(name)?.Value.Trim();

        return string.IsNullOrWhiteSpace(value) ? null : value;
    }

    /// <summary>
    /// Playtime is minutes, as an invariant decimal. Anything else is a layout this adapter does not
    /// know, and an unreadable playtime costs a line rather than a slot.
    /// </summary>
    private static string? Playtime(string? raw)
    {
        if (raw is null || double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out var minutes) is false)
        {
            return null;
        }

        var played = TimeSpan.FromMinutes(minutes);

        // Hours, because a farm's playtime is measured in tens of them and "1.21:37:00" is not a
        // number anybody reads.
        return played < TimeSpan.FromHours(1)
            ? $"{played.TotalMinutes:N0} min"
            : $"{played.TotalHours:N0} h";
    }

    private static string? Money(string? raw)
    {
        return raw is not null && double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out var amount)
            ? amount.ToString("N0", CultureInfo.CurrentCulture)
            : null;
    }

    /// <summary>The game writes these in caps, which reads as shouting in a list of sentences.</summary>
    private static string? Difficulty(string? raw)
    {
        return string.IsNullOrWhiteSpace(raw)
            ? null
            : string.Concat(raw[..1].ToUpperInvariant(), raw[1..].ToLowerInvariant());
    }

    private static string? LastWrittenText(string careerFile)
    {
        try
        {
            return File.GetLastWriteTime(careerFile).ToString("g", CultureInfo.CurrentCulture);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            return null;
        }
    }

    /// <summary>
    /// None for a career file that cannot be read as one - which is not an error here, only an
    /// unnamed slot. A game that is mid-write holds the file, and a save from a version this adapter
    /// does not know may not carry the element at all.
    /// </summary>
    private static Maybe<XElement> ReadCareer(string careerFile)
    {
        return
            from document in ReadXml(careerFile)
            from root in Maybe.From(document.Element("careerSavegame"))
            select root;
    }

    private static Maybe<XDocument> ReadXml(string path)
    {
        try
        {
            var settings = new XmlReaderSettings
            {
                DtdProcessing = DtdProcessing.Prohibit,
                XmlResolver = null
            };

            using var reader = XmlReader.Create(path, settings);

            return Maybe.From(XDocument.Load(reader));
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or XmlException)
        {
            return Maybe<XDocument>.None;
        }
    }
}
