using ModsDude.Client.Core.Exceptions;
using ModsDude.Client.Core.GameAdapters.DynamicForms;
using ModsDude.Client.Core.Models;
using System.Xml.Linq;

namespace ModsDude.Client.Core.GameAdapters.Implementations.FarmingSimulatorV1;

public class FarmingSimulatorBaseSavegameAdapter : IBaseSavegameAdapter
{
    /// <summary>
    /// Farming Simulator has a fixed set of numbered folders and no way to add another, so a save
    /// always displaces or fills one that is already there.
    /// </summary>
    public bool CanCreateSlots => false;


    public IInstanceSavegameAdapter WithInstanceSettings(string serializedInstanceSettings)
    {
        var settings = FarmingSimulatorInstanceSettings.Deserialize(serializedInstanceSettings);
        settings.EnsureValid();
        return new FarmingSimulatorInstanceSavegameAdapter(settings);
    }

    public IInstanceSavegameAdapter WithInstanceSettings(DynamicForm instanceSettings)
    {
        if (instanceSettings is not FarmingSimulatorInstanceSettings settings)
        {
            throw new IncorrectGameAdapterSettingsTypeException<FarmingSimulatorInstanceSettings>(instanceSettings);
        }
        settings.EnsureValid();
        return new FarmingSimulatorInstanceSavegameAdapter(settings);
    }
}

public class FarmingSimulatorInstanceSavegameAdapter(FarmingSimulatorInstanceSettings settings)
    : FarmingSimulatorBaseSavegameAdapter, IInstanceSavegameAdapter
{
    /// <summary>
    /// The game offers this many save slots and no more. It is a number about one game, which is
    /// exactly why it lives here and why <see cref="IInstanceSavegameAdapter.GetSlots"/> returns a
    /// list - nothing above this file has to know it.
    /// </summary>
    private const int _slotCount = 20;

    /// <summary>
    /// The file every started save has, and the only one read to describe a slot. Its absence is how
    /// an empty slot is told from an occupied one.
    /// </summary>
    private const string _careerSavegameFile = "careerSavegame.xml";

    /// <summary>
    /// Regenerated by the game from the save it sits beside, so it is bulk that would make every
    /// check-in bigger and make the content hash differ for a reason nobody played.
    /// </summary>
    private static readonly string[] _excludedFileNames = ["screenshot.png"];


    public string GetSlotPath(SavegameSlotId slot)
    {
        return Path.Join(settings.GameDataFolder, slot.Value);
    }

    public async Task<IReadOnlyList<SavegameSlot>> GetSlots(CancellationToken cancellationToken)
    {
        var slots = new List<SavegameSlot>(_slotCount);

        for (var number = 1; number <= _slotCount; number++)
        {
            cancellationToken.ThrowIfCancellationRequested();

            slots.Add(await ReadSlot(new SavegameSlotId($"savegame{number}"), cancellationToken));
        }

        return slots;
    }

    public bool BelongsInPackedSave(string relativePath)
    {
        return !_excludedFileNames.Contains(Path.GetFileName(relativePath), StringComparer.OrdinalIgnoreCase);
    }


    /// <summary>
    /// Describes one slot from its career file.
    /// </summary>
    /// <remarks>
    /// <b>Degrades rather than throws.</b> A slot whose career file is missing is empty; one whose
    /// career file will not parse, or is being written by a running game, is occupied and unnamed.
    /// Reporting it as empty would be the one mistake that matters here, because an empty slot is
    /// the one the engine overwrites without asking.
    /// </remarks>
    private async Task<SavegameSlot> ReadSlot(SavegameSlotId id, CancellationToken cancellationToken)
    {
        var careerFile = Path.Join(GetSlotPath(id), _careerSavegameFile);

        return await Task.Run(() =>
        {

            if (!File.Exists(careerFile))
            {
                return new SavegameSlot(id, null, false, null, null);
            }

            var lastModified = File.GetLastWriteTime(careerFile);

            try
            {
                var settings = XDocument.Load(careerFile).Root?.Element("settings");

                var name = settings?.Element("savegameName")?.Value;
                var playTime = settings?.Element("playTime")?.Value;

                return new SavegameSlot(
                    id,
                    string.IsNullOrWhiteSpace(name) ? null : name,
                    true,
                    lastModified,
                    // Minutes, as a decimal. Anything else is a layout this adapter does not know,
                    // and a missing playtime costs a column rather than a slot.
                    double.TryParse(playTime, System.Globalization.CultureInfo.InvariantCulture, out var minutes)
                        ? TimeSpan.FromMinutes(minutes)
                        : null);
            }
            catch (Exception exception) when (exception is IOException or UnauthorizedAccessException or System.Xml.XmlException)
            {
                return new SavegameSlot(id, null, true, lastModified, null);
            }
        }, cancellationToken);
    }
}
