using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using ModsDude.Client.Core.Exceptions;
using ModsDude.Client.Core.GameAdapters.DynamicForms;
using ModsDude.Client.Core.Helpers;
using ModsDude.Client.Core.Models;
using System.Globalization;
using System.Xml;
using System.Xml.Linq;

namespace ModsDude.Client.Core.GameAdapters.Implementations.FarmingSimulatorV1;

public class FarmingSimulatorBaseSavegameAdapter(ILoggerFactory? loggerFactory = null) : IBaseSavegameAdapter
{
    /// <summary>
    /// Everything here degrades rather than throws, so a slot that reads as unnamed and
    /// undescribed looks exactly like one the user has never touched. This is where the difference
    /// is written down.
    /// </summary>
    protected ILogger Log { get; } = loggerFactory?.CreateLogger<FarmingSimulatorBaseSavegameAdapter>()
        ?? NullLogger<FarmingSimulatorBaseSavegameAdapter>.Instance;

    protected ILoggerFactory? Loggers { get; } = loggerFactory;

    /// <summary>
    /// Farming Simulator has a fixed set of numbered folders and no way to add another, so a save
    /// always fills or displaces one that is already there.
    /// </summary>
    public bool CanCreateSlots => false;


    public IInstanceSavegameAdapter WithInstanceSettings(string serializedInstanceSettings)
    {
        var instanceSettings = FarmingSimulatorInstanceSettings.Deserialize(serializedInstanceSettings);
        instanceSettings.EnsureValid();
        return new FarmingSimulatorInstanceSavegameAdapter(instanceSettings, Loggers);
    }

    public IInstanceSavegameAdapter WithInstanceSettings(DynamicForm instanceSettings)
    {
        if (instanceSettings is not FarmingSimulatorInstanceSettings settings)
        {
            throw new IncorrectGameAdapterSettingsTypeException<FarmingSimulatorInstanceSettings>(instanceSettings);
        }
        settings.EnsureValid();
        return new FarmingSimulatorInstanceSavegameAdapter(settings, Loggers);
    }
}


public class FarmingSimulatorInstanceSavegameAdapter(
    FarmingSimulatorInstanceSettings instanceSettings,
    ILoggerFactory? loggerFactory = null)
    : FarmingSimulatorBaseSavegameAdapter(loggerFactory), IInstanceSavegameAdapter
{
    /// <summary>
    /// The game offers this many slots and no more. A number about one game, which is exactly why it
    /// lives here and why <see cref="IInstanceSavegameAdapter.GetSlots"/> hands back a list - nothing
    /// above this file has to know it.
    /// </summary>
    private const int _slotCount = 20;

    /// <summary>
    /// The file every started save has, and the one that names it. Its absence is how an empty slot
    /// is told from an occupied one.
    /// </summary>
    private const string _careerSavegameFile = "careerSavegame.xml";

    /// <summary>
    /// Where the players who have connected are recorded. The career file says nothing about
    /// multiplayer, so this is the only place that question can be answered from.
    /// </summary>
    private const string _farmsFile = "farms.xml";

    /// <summary>
    /// Regenerated by the game from the save beside it, so it is bulk that would make every check-in
    /// bigger and make the content hash differ for a reason nobody played.
    /// </summary>
    private static readonly string[] _excludedFileNames = ["screenshot.png"];


    private string GameDataFolder => instanceSettings.GameDataFolder
        ?? throw new InvalidOperationException("Instance settings carry no game data folder.");


    public string GetSlotPath(SavegameSlotId slot)
    {
        return Path.Combine(GameDataFolder, slot.Value);
    }

    /// <summary>
    /// Every slot, in the order the game numbers them.
    /// </summary>
    /// <remarks>
    /// Read in parallel, capped the way the mod scan is: this is disk bound, so a handful at a time
    /// is as quick as twenty, and the thread pool belongs to the rest of the app too. Indexed rather
    /// than collected, so the results keep the slot order rather than the order they finished in.
    /// </remarks>
    public Task<IReadOnlyList<SavegameSlot>> GetSlots(CancellationToken cancellationToken)
    {
        return Task.Run<IReadOnlyList<SavegameSlot>>(() =>
        {
            var slots = new SavegameSlot[_slotCount];

            var options = new ParallelOptions
            {
                MaxDegreeOfParallelism = Environment.ProcessorCount,
                CancellationToken = cancellationToken
            };

            Parallel.For(0, _slotCount, options, i =>
            {
                var id = new SavegameSlotId($"savegame{i + 1}");
                slots[i] = ReadSlot(id, GetSlotPath(id), Log, cancellationToken);
            });

            return slots;
        }, cancellationToken);
    }

    public bool BelongsInPackedSave(string relativePath)
    {
        return !_excludedFileNames.Contains(Path.GetFileName(relativePath), StringComparer.OrdinalIgnoreCase);
    }


    /// <summary>
    /// One slot, described from its career file and the farms beside it.
    /// </summary>
    /// <remarks>
    /// <b>Degrades rather than throws</b>, and always in the same direction. A slot whose career file
    /// is missing is empty; one whose career file will not parse, or that a running game is writing,
    /// is <b>occupied and unnamed</b>. Reporting it as empty is the single mistake that matters here,
    /// because an empty slot is the one the engine writes to without asking. Every detail is likewise
    /// optional - a field this adapter cannot read costs that one line and nothing else.
    /// </remarks>
    internal static SavegameSlot ReadSlot(SavegameSlotId id, string slotPath, ILogger log, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var careerFile = Path.Combine(slotPath, _careerSavegameFile);

        if (!File.Exists(careerFile))
        {
            return new SavegameSlot(id, null, false, []);
        }

        var maybeCareer = ReadCareer(careerFile, log);
        if (maybeCareer.HasValue is false)
        {
            // Warning rather than debug: the user is looking at "a save this game will not name" and
            // has no other way to find out why. A game that is mid-write is the innocent cause and
            // the reason this is not louder still.
            log.LogWarning("Slot {Slot} has a career file that could not be read; it will show as unnamed.", id.Value);

            return new SavegameSlot(id, null, true, []);
        }

        var career = maybeCareer.Value;
        var settings = Maybe.From(career.Element("settings"));

        var name =
            from element in settings
            from savegameName in Maybe.From(element.Element("savegameName"))
            let value = savegameName.Value.Trim()
            where string.IsNullOrWhiteSpace(value) is false
            select value;

        return new SavegameSlot(
            id,
            name.HasValue ? name.Value : null,
            true,
            ReadDetails(career, settings, slotPath, careerFile, log));
    }


    /// <summary>
    /// What this game is worth saying about a save, in the order somebody reads it: where they are
    /// playing, how the farm is doing, when they last played, and then the rest.
    /// </summary>
    /// <remarks>
    /// <b>Money is second because a row only shows the first few.</b> Where and how much are the two
    /// facts that tell two saves of the same map apart at a glance - a bank balance says how far along
    /// a farm is in a way a creation date does not - so it goes above "Started", which was pushing it
    /// off the row and into the tooltip.
    /// </remarks>
    private static IReadOnlyList<SavegameDetail> ReadDetails(
        XElement career, Maybe<XElement> settings, string slotPath, string careerFile, ILogger log)
    {
        var details = new List<SavegameDetail>();

        void Add(string detailId, string label, string? value)
        {
            if (string.IsNullOrWhiteSpace(value) is false)
            {
                details.Add(new SavegameDetail(detailId, label, value.Trim()));
            }
        }

        // Under <statistics>, not <settings> - which is where playtime used to look, so every slot
        // silently reported none at all.
        var statistics = Maybe.From(career.Element("statistics"));
        var farms = ReadFarms(slotPath, log);

        Add(SavegameDetail.Ids.Map, "Map", Text(settings, "mapTitle"));
        Add(SavegameDetail.Ids.Money, "Money", MoneyText(farms, Text(statistics, "money"), log));

        // The game's own record of when it was last written, which stays honest where copying the
        // save between machines has rewritten the file's own timestamp. That timestamp is the
        // fallback, because a save with no saveDate still has a "when" worth showing.
        Add(SavegameDetail.Ids.LastPlayed, "Last played",
            Text(settings, "saveDate") ?? LastWrittenText(careerFile, log));

        Add(SavegameDetail.Ids.Started, "Started", Text(settings, "creationDate"));
        Add(SavegameDetail.Ids.Playtime, "Played", Playtime(Text(statistics, "playTime"), log));
        Add(SavegameDetail.Ids.Difficulty, "Difficulty", Difficulty(Text(settings, "economicDifficulty")));
        Add(SavegameDetail.Ids.Multiplayer, "Multiplayer", MultiplayerText(farms));

        return details;
    }

    /// <summary>
    /// One farm's balance, and which farm it is where that is a question.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Money is a property of a farm, not of a save.</b> It lives on the <c>farm</c> element in
    /// <c>farms.xml</c>, and a multiplayer save has several - one per farm somebody started, plus the
    /// shop's, which has no money of its own. There is no single number, so this shows the
    /// <b>first real farm's</b>, which is the host's in every save anybody actually plays, and names
    /// the farm whenever there is more than one so that the number is attributable rather than
    /// mysterious.
    /// </para>
    /// <para>
    /// <c>&lt;statistics&gt;&lt;money&gt;</c> in the career file is the fallback and nothing more. It
    /// is what older saves in the series carried, it is absent or stale in the current ones, and
    /// preferring it is how this detail came to show nothing at all.
    /// </para>
    /// </remarks>
    private static string? MoneyText(IReadOnlyList<Farm> farms, string? careerMoney, ILogger log)
    {
        if (farms.FirstOrDefault(x => x.Money is not null) is not Farm farm)
        {
            return Money(careerMoney, log);
        }

        var amount = farm.Money!.Value.ToString("N0", CultureInfo.CurrentCulture);

        // Named only where naming it distinguishes anything. In a singleplayer save the farm is "the
        // farm", and appending its name to every balance would be noise on the one row that has least
        // room for it.
        return farms.Count > 1 && string.IsNullOrWhiteSpace(farm.Name) is false
            ? $"{amount} ({farm.Name.Trim()})"
            : amount;
    }

    /// <summary>
    /// Whether more than one person has ever joined, counted from the farms' player lists.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The career file records nothing about multiplayer, so this comes from <c>farms.xml</c>, where
    /// every farm keeps the players that have connected to it. One player is a save somebody has
    /// only ever played alone; more than one is a save that has been shared.
    /// </para>
    /// <para>
    /// <b>A heuristic, and worded as one.</b> It answers "has anybody else been in here", which is
    /// what somebody about to publish a save is actually asking. It cannot tell a game that was
    /// hosted and never joined from a singleplayer one, and does not pretend to.
    /// </para>
    /// <para>
    /// The farm count rides along where there is more than one, because that is the other half of the
    /// same question: four people on one farm and four people on four farms are different evenings,
    /// and it is also what says which farm the balance above belongs to.
    /// </para>
    /// </remarks>
    private static string? MultiplayerText(IReadOnlyList<Farm> farms)
    {
        // Distinct across every farm: one person who has joined two farms is still one person, and
        // the shop farm carries no players at all.
        var players = farms
            .SelectMany(x => x.PlayerIds)
            .Distinct(StringComparer.Ordinal)
            .Count();

        var occupied = farms.Count(x => x.PlayerIds.Count > 0);
        var across = occupied > 1 ? $" across {occupied} farms" : "";

        return players switch
        {
            0 => null,
            1 => "No, only ever played alone",
            _ => $"Yes, {players} players have joined{across}"
        };
    }

    /// <summary>
    /// The save's farms, in the order the game numbers them, with the shop farm left out.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Read once and handed to everything that needs it. Money and the multiplayer heuristic are two
    /// questions about the same file, and opening it twice per slot - twenty slots deep, on every
    /// listing - is a cost with nothing to show for it.
    /// </para>
    /// <para>
    /// Farm 0 is the shop rather than somebody's farm: it exists in every save, has no players and no
    /// balance worth reporting, and including it would make "the first farm" the wrong one in every
    /// save there is. Anything the file numbers oddly, or does not number at all, is kept - a farm
    /// this adapter cannot place is still a farm, and dropping it would lose a balance.
    /// </para>
    /// <para>
    /// Empty for a save with no <c>farms.xml</c>, which is not a fault: a savegame from a version that
    /// did not write one still has a career file, and every detail here is optional by design.
    /// </para>
    /// </remarks>
    private static IReadOnlyList<Farm> ReadFarms(string slotPath, ILogger log)
    {
        var farmsFile = Path.Combine(slotPath, _farmsFile);

        if (File.Exists(farmsFile) is false)
        {
            return [];
        }

        var document = ReadXml(farmsFile, log);

        if (document.HasValue is false)
        {
            return [];
        }

        var farms = new List<Farm>();

        foreach (var element in document.Value.Descendants("farm"))
        {
            var id = Number((string?)element.Attribute("farmId"));

            if (id == 0)
            {
                continue;
            }

            farms.Add(new Farm(
                id,
                (string?)element.Attribute("name"),
                // The attribute is where the current games put it; the child element is where a
                // version that moves it would most plausibly put it instead, and reading both costs
                // one lookup on a document already in memory.
                Money(element),
                [.. element.Descendants("player")
                    .Select(x => (string?)x.Attribute("uniqueUserId"))
                    .Where(x => string.IsNullOrWhiteSpace(x) is false)
                    .Select(x => x!)]));
        }

        return [.. farms.OrderBy(x => x.Id ?? int.MaxValue)];
    }

    private static double? Money(XElement farm)
    {
        var raw = (string?)farm.Attribute("money") ?? farm.Element("money")?.Value;

        return raw is not null && double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out var amount)
            ? amount
            : null;
    }

    private static int? Number(string? raw)
        => int.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out var value) ? value : null;


    /// <param name="Id">Null where the file numbered it in a way this adapter does not read. Sorted last, never dropped.</param>
    private sealed record Farm(int? Id, string? Name, double? Money, IReadOnlyList<string> PlayerIds);

    private static string? Text(Maybe<XElement> parent, string name)
    {
        if (parent.HasValue is false)
        {
            return null;
        }

        var value = parent.Value.Element(name)?.Value.Trim();

        return string.IsNullOrWhiteSpace(value) ? null : value;
    }

    /// <summary>
    /// Playtime is minutes, as an invariant decimal. Anything else is a layout this adapter does not
    /// know, and an unreadable playtime costs a line rather than a slot.
    /// </summary>
    private static string? Playtime(string? raw, ILogger log)
    {
        if (raw is null)
        {
            return null;
        }

        if (double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out var minutes) is false)
        {
            // The element was there and this adapter could not read it, which is a layout change
            // rather than a save that simply does not record playtime. Worth telling apart.
            log.LogDebug("Could not read '{Value}' as a playtime in minutes.", raw);

            return null;
        }

        var played = TimeSpan.FromMinutes(minutes);

        // Hours, because a farm's playtime is measured in tens of them and "1.21:37:00" is not a
        // number anybody reads.
        return played < TimeSpan.FromHours(1)
            ? $"{played.TotalMinutes:N0} min"
            : $"{played.TotalHours:N0} h";
    }

    private static string? Money(string? raw, ILogger log)
    {
        if (raw is null)
        {
            return null;
        }

        if (double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out var amount) is false)
        {
            log.LogDebug("Could not read '{Value}' as a money balance.", raw);

            return null;
        }

        return amount.ToString("N0", CultureInfo.CurrentCulture);
    }

    /// <summary>The game writes these in caps, which reads as shouting in a list of sentences.</summary>
    private static string? Difficulty(string? raw)
    {
        return string.IsNullOrWhiteSpace(raw)
            ? null
            : string.Concat(raw[..1].ToUpperInvariant(), raw[1..].ToLowerInvariant());
    }

    private static string? LastWrittenText(string careerFile, ILogger log)
    {
        try
        {
            return File.GetLastWriteTime(careerFile).ToString("g", CultureInfo.CurrentCulture);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            log.LogDebug(exception, "Could not read when {File} was last written.", careerFile);

            return null;
        }
    }

    /// <summary>
    /// None for a career file that cannot be read as one - which is not an error here, only an
    /// unnamed slot. A game that is mid-write holds the file, and a save from a version this adapter
    /// does not know may not carry the element at all.
    /// </summary>
    private static Maybe<XElement> ReadCareer(string careerFile, ILogger log)
    {
        return
            from document in ReadXml(careerFile, log)
            from root in Maybe.From(document.Element("careerSavegame"))
            select root;
    }

    private static Maybe<XDocument> ReadXml(string path, ILogger log)
    {
        try
        {
            var settings = new XmlReaderSettings
            {
                DtdProcessing = DtdProcessing.Prohibit,
                XmlResolver = null
            };

            using var reader = XmlReader.Create(path, settings);

            return Maybe.From(XDocument.Load(reader));
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or XmlException)
        {
            // The caller decides how loudly this matters - a career file that will not open is a
            // slot the user can see is wrong, and farms.xml is one missing line - so the exception
            // itself is recorded here and the consequence is said there.
            log.LogDebug(ex, "Could not read {File} as XML.", path);

            return Maybe<XDocument>.None;
        }
    }
}
