#!/bin/bash
set -euo pipefail

# $1 = path to the idempotent SQL migration script generated by `dotnet ef migrations script --idempotent`.
# Copied fresh onto the server on every deploy, so it never drifts from what's committed here.

psql "$(cat ~/modsdude/shared/database-url)" -v ON_ERROR_STOP=1 -f "$1"
